### ISSUE TITLE
[Feature] Custom previewer

### ISSUE THREAD

**Issue by pidgeon777** [jan-xyz/lsp-preview.nvim#1]
First of all, congratulations on your project.

Secondly, I would suggest to also add custom previewers such as `delta`.

Something has been already implemented here:

https://neovimcraft.com/plugin/aznhe21/actions-preview.nvim

**Comment by jan-xyz** [comment]
Thanks for the feedback. Adding custom cli output is not something I'm planning to support. The first priority for now is to find a way to display individual TextEdits instead of summarizing everything by file. For that, I have a strong tendency to rather let it behave like a proper file buffer to highlight individual lines. It all is a bit uncertain though and my stance on that might change depending on the work of that feature.

**Comment by jan-xyz** [comment]
I'm closing this in favour of #3 and also added it to a new FAQ section in the README.
